name: Deployment

on:
  push:
    paths:
      - ".github/workflows/deployment.yaml"
      - ".github/workflows/deployment-reusable.yaml"
      - "applications/**"
    branches:
      - main

jobs:
  setup:
    strategy:
      matrix:
        app-name: [demo, example]
    uses: crgeary/alpha/.github/workflows/deployment-reusable.yml@main
    with:
      app-name: ${{ matrix.target }}
